# Generated by Django 3.1.1 on 2020-09-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='System_name',
            new_name='system_name',
        ),
    ]
